{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "todo-vue.fullname" . }}
  labels:
    {{- include "todo-vue.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  {{- if .Values.route.path }}
  path: {{ .Values.route.path | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "todo-vue.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    {{- if .Values.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | quote }}
    {{- end }}
  {{- end }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy | default "None" }}
{{- end }}
