{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "todo-vue.serviceAccountName" . }}
  labels:
    {{- include "todo-vue.labels" . | nindent 4 }}
{{- end }}
