apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-vue.fullname" . }}
  labels:
    {{- include "todo-vue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "todo-vue.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
